Update deleting-vaults-cli.md
awsdocs/amazon-glacier-developer-guide pull request #9
Opened 2021-02-02 01:02 UTC by kmrbrierley

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-02-02 12:13 UTC, kmrbrierley commented
https://github.com/aws/aws-cli/issues/2486
this solution was proposed above but not propagated to documentation.
I can confirm it worked for me

2021-02-02 19:58 UTC, aws-alan requested changes

2021-02-02 19:58 UTC, aws-alan commented on doc_source/deleting-vaults-cli.md
> +The archiveid can start with a "-" this confuses the argument parser if the normal form of --archive-id "-asdfasdf" is used.  using the form --archive-id="-asdfasdf" seems to work reliably
This sentence (115) is not written in the same style and voice as the rest of this page. If we remove this we can merge the request.

2021-11-23 23:34 UTC, aws-alan commented
This has been fixed upstream and will be reflected next time the docs are refreshed.

2021-11-23 23:34 UTC, closed without merging